FROM python:3.12-slim

ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1 \
    DB_ENGINE=mysql

WORKDIR /app

COPY requirements-cloud-mysql.txt /app/requirements-cloud-mysql.txt
RUN pip install --no-cache-dir -r /app/requirements-cloud-mysql.txt

COPY api /app/api

EXPOSE 8000
CMD ["uvicorn", "api.main:app", "--host", "0.0.0.0", "--port", "8000"]
